plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/user/Downloads/Are you the On App/privacy-policy"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/user/Downloads/Are you the On App/privacy-policy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]